// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm_E8IcYZ7ei3dOHD2Wvmj1SuvfkBRDmQ',
    appId: '1:99533548908:android:b16d0ee2be5306ad335749',
    messagingSenderId: '99533548908',
    projectId: 'moviestestapp',
    storageBucket: 'moviestestapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo_TBMyOD2nzOqt4oMXBIRiX2RR3BXJ5Q',
    appId: '1:99533548908:ios:c595ec0b8371db5b335749',
    messagingSenderId: '99533548908',
    projectId: 'moviestestapp',
    storageBucket: 'moviestestapp.appspot.com',
    iosClientId: '99533548908-f98tef76t4qo1jq5mkgre9prat9fvfm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesapp',
  );
}
